//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;

    public partial class DoctorSchedule
    {
        public int DoctorScheduleID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<int> TimeFrom { get; set; }
        public Nullable<int> TimeFromMeridiemID { get; set; }
        public Nullable<int> TimeTo { get; set; }
        public Nullable<int> TimeToMeridiemID { get; set; }
        public virtual DayMaster DayMaster { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual MeridiemMaster MeridiemMaster { get; set; }
        public virtual MeridiemMaster MeridiemMaster1 { get; set; }
    }
}
