//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDocumentUpload
    {
        public int Id { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public byte[] SalarySlip { get; set; }
        public byte[] PFSlip { get; set; }
        public byte[] ESISlip { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> JobRegistrationId { get; set; }
    
        public virtual JobRegistration JobRegistration { get; set; }
    }
}
