//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobRegistration()
        {
            this.JobRegistrationEmployements = new HashSet<JobRegistrationEmployement>();
            this.JobRegistrationLanguages = new HashSet<JobRegistrationLanguage>();
            this.JobRegistrationQualifications = new HashSet<JobRegistrationQualification>();
            this.JobRegistrationSkills = new HashSet<JobRegistrationSkill>();
            this.JobDocumentUploads = new HashSet<JobDocumentUpload>();
            this.JobResignations = new HashSet<JobResignation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string Religion { get; set; }
        public string IdentityType { get; set; }
        public string IdentityNo { get; set; }
        public string MobileNo { get; set; }
        public string AlternateNo { get; set; }
        public string EmailId { get; set; }
        public string Pincode { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> StateId { get; set; }
        public byte[] Resume { get; set; }
        public byte[] ResumeImage { get; set; }
        public string Experience { get; set; }
        public Nullable<bool> Disability { get; set; }
        public Nullable<bool> ExServiceMan { get; set; }
        public Nullable<decimal> PersonHeight { get; set; }
        public string EyeSight { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Password { get; set; }
        public string EmployementStatus { get; set; }
        public Nullable<int> VendorId { get; set; }
    
        public virtual City City { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRegistrationEmployement> JobRegistrationEmployements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRegistrationLanguage> JobRegistrationLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRegistrationQualification> JobRegistrationQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRegistrationSkill> JobRegistrationSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDocumentUpload> JobDocumentUploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobResignation> JobResignations { get; set; }
        public virtual VendorDetail VendorDetail { get; set; }
    }
}
