//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRegistrationEmployement
    {
        public int Id { get; set; }
        public string OrganizationName { get; set; }
        public string Post { get; set; }
        public string FromMonth { get; set; }
        public string FromYear { get; set; }
        public string ToMonth { get; set; }
        public string ToYear { get; set; }
        public string IndustryType { get; set; }
        public string Salary { get; set; }
        public Nullable<int> RegistrationId { get; set; }
    
        public virtual JobRegistration JobRegistration { get; set; }
    }
}
