//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorProject
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string DepartmentName { get; set; }
        public string WorkDescription { get; set; }
        public byte[] Image { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
    }
}
