//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] PageHeaderImage { get; set; }
        public byte[] SliderImage { get; set; }
        public string Caption { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string ServiceDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
