//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorJob()
        {
            this.JobRegistrations = new HashSet<JobRegistration>();
        }
    
        public int Id { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Jobtype { get; set; }
        public Nullable<int> NoofRequirement { get; set; }
        public string SkillsRequired { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRegistration> JobRegistrations { get; set; }
        public virtual VendorDetail VendorDetail { get; set; }
        public virtual VendorJob VendorJob1 { get; set; }
        public virtual VendorJob VendorJob2 { get; set; }
    }
}
